server:
  host: "0.0.0.0"
  port: 8080

secret: "np5CSGPjSzinGdgZuQ2b"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "ne-noy"
  sslmode: "disable"
  timezone: "UTC"